{
    "openapi": "3.0.1",
    "info": {
        "title": "CRM Associations Schema",
        "version": "v4",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "STARTER"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "To associate a contact with a company, use this API to get the necessary associationTypeId and associationCategory.",
        "x-hubspot-related-documentation": [
            {
                "name": "Associations Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/associations"
            }
        ],
        "x-hubspot-introduction": "Use the association schema API to understand how different types of CRM records and activities can relate to one another, as well as define your own custom associations. "
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v4/associations"
        }
    ],
    "tags": [
        {
            "name": "Definition Configurations"
        },
        {
            "name": "Definitions"
        }
    ],
    "paths": {
        "/definitions/configurations/all": {
            "get": {
                "tags": [
                    "Definition Configurations"
                ],
                "summary": "Retrieve all association definitions",
                "description": "Returns all user configurations available on a given portal",
                "operationId": "get-/crm/v4/associations/definitions/configurations/all_getAll",
                "security": [
                    {
                        "private_apps": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "contacts"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            }
        },
        "/definitions/configurations/{fromObjectType}/{toObjectType}": {
            "get": {
                "tags": [
                    "Definition Configurations"
                ],
                "summary": "Get configs between two object types",
                "description": "Returns user-defined association configurations for all association definitions between the specified object types.",
                "operationId": "get-/crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}_getAllBetweenTwoObjectTypes",
                "security": [
                    {
                        "private_apps": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "contacts"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            }
        },
        "/definitions/configurations/{fromObjectType}/{toObjectType}/batch/create": {
            "post": {
                "tags": [
                    "Definition Configurations"
                ],
                "summary": "Batch create association configs",
                "description": "Creates multiple user-defined association configurations between the specified object types in a single batch.",
                "operationId": "post-/crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}/batch/create_batchCreate",
                "security": [
                    {
                        "private_apps": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "contacts"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            }
        },
        "/{fromObjectType}/{toObjectType}/labels": {
            "get": {
                "tags": [
                    "Definitions"
                ],
                "summary": "Retrieve all association labels",
                "description": "Returns all association labels for the defined relationship between the specified object types.",
                "operationId": "get-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels_getAll",
                "security": [
                    {
                        "private_apps": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "contacts"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            },
            "put": {
                "tags": [
                    "Definitions"
                ],
                "summary": "Update an association definition",
                "description": "Updates an existing user-defined association definition between two object types",
                "operationId": "put-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels_update",
                "security": [
                    {
                        "private_apps": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "contacts"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            },
            "post": {
                "tags": [
                    "Definitions"
                ],
                "summary": "Create an association definition",
                "description": "Creates a new user-defined association definition between two object types",
                "operationId": "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels_create",
                "security": [
                    {
                        "private_apps": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "contacts"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            }
        },
        "/definitions/configurations/{fromObjectType}/{toObjectType}/batch/purge": {
            "post": {
                "tags": [
                    "Definition Configurations"
                ],
                "summary": "Batch delete configurations",
                "description": "Deletes multiple user-defined association configurations between the specified object types in a single batch",
                "operationId": "post-/crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}/batch/purge_batchRemove",
                "security": [
                    {
                        "private_apps": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "contacts"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            }
        },
        "/{fromObjectType}/{toObjectType}/labels/{associationTypeId}": {
            "delete": {
                "tags": [
                    "Definitions"
                ],
                "summary": "Delete an association definition",
                "description": "Deletes the association definition corresponding to the specified association type ID between two object types",
                "operationId": "delete-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels/{associationTypeId}_remove",
                "security": [
                    {
                        "private_apps": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "contacts"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            }
        },
        "/definitions/configurations/{fromObjectType}/{toObjectType}/batch/update": {
            "post": {
                "tags": [
                    "Definition Configurations"
                ],
                "summary": "Batch update configurations",
                "description": "Updates multiple user-defined association configurations between the specified object types in a single batch",
                "operationId": "post-/crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}/batch/update_batchUpdate",
                "security": [
                    {
                        "private_apps": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "contacts"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.subscriptions.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "media_bridge.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.companies.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.users.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "tickets"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.goals.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.orders.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.commercepayments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.deals.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.appointments.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.invoices.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.leads.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.leads.read"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.custom.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.courses.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.listings.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.courses.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.quotes.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.services.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.partner-clients.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.quotes.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "e-commerce": "e-commerce",
                            "crm.objects.custom.write": "Change custom object records",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.goals.read": "Read goals",
                            "tickets": "Read and write tickets",
                            "crm.objects.custom.read": "View custom object records"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.contacts.read": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.deals.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.companies.write": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.orders.read": "Read Orders"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "PHP",
        "Node",
        "Ruby",
        "Python"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "STARTER"
    },
    "x-hubspot-documentation-banner": "NONE"
}