[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.associations.schema"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot" ,"crm" ,"associations" ,"schema"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.associations.schema"

[build-options]
observabilityIncluded = true
